// Code generated by Slice Machine. DO NOT EDIT.

import ArticleFullBleed from "./ArticleFullBleed/index.svelte";
import ArticleHeader from "./ArticleHeader/index.svelte";
import ArticleImageBlock from "./ArticleImageBlock/index.svelte";
import ArticleNumberedGrid from "./ArticleNumberedGrid/index.svelte";
import ArticleTextBlock from "./ArticleTextBlock/index.svelte";
import StaticBioBlock from "./StaticBioBlock/index.svelte";

export const components = {
  article_full_bleed: ArticleFullBleed,
  article_header: ArticleHeader,
  article_image_block: ArticleImageBlock,
  article_numbered_grid: ArticleNumberedGrid,
  article_text_block: ArticleTextBlock,
  static_bio_block: StaticBioBlock,
};
