// Code generated by Slice Machine. DO NOT EDIT.

import ArticleHeader from "./ArticleHeader/index.svelte";
import Bio from "./Bio/index.svelte";
import FullWidthImage from "./FullWidthImage/index.svelte";
import ImageBlock from "./ImageBlock/index.svelte";
import NumberedGrid from "./NumberedGrid/index.svelte";
import TextBlock from "./TextBlock/index.svelte";

export const components = {
  article_header: ArticleHeader,
  bio: Bio,
  full_width_image: FullWidthImage,
  image_block: ImageBlock,
  numbered_grid: NumberedGrid,
  text_block: TextBlock,
};
